---
- name: Install ssh keys
  copy:
    src: "ssh/{{ item }}"
    mode: "0644"
    dest: ~/.ssh/
  with_items:
    - id_rsa
    - id_rsa.pub
    - known_hosts

- name: Install ssh config
  copy:
    src: "ssh/config"
    mode: "0644"
    dest: ~/.ssh/
